### ISSUE TITLE
Aimbot mode 1: aimbot flicks when shooting at teammate

### ISSUE THREAD

**Issue by Dr4inder** [ReyKoxha/Quartus_PUB#10]
**Aimbot mode 1:**
When shooting at a teammate, the aimbot flicks (depends on smooth) with huge fov to next enemy

**Comment by ReyKoxha** [comment]
Will investigate this. Thanks for reporting.

**Comment by ReyKoxha** [comment]
Can you please retry with the latest release?

**Comment by Dr4inder** [comment]
Tried with latest release. Still the same
https://streamable.com/y19kv

**Comment by ziez456** [comment]
@Dr4inder Really weird
I don't have that..

**Comment by ziez456** [comment]
@Dr4inder Why do u use smooth 0?
Smooth stands for smoothing the lock so it goes slower and smoother towards the aimpoint like the head (8) i would suggest the smooth between atleast 30 - **

**Comment by Dr4inder** [comment]
The bug is that the aimbot is somehow active when my crosshair is close to TEAMMATES and snaps to the Enemy. It doesn't have to do with smooth. Normally it shouldn't do anything if I shoot close to teammates.

**Comment by ziez456** [comment]
@Dr4inder hmm really weird man
