### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by SlicedDev** [ReyKoxha/Quartus_PUB#11]
When using ESP mode 2 csgo crashes instantly or in 5-10 mins

**Comment by pakboy** [comment]
same :)

**Comment by SlicedDev** [comment]
@pakboy i fixed them by myself xd

**Comment by zmqcros** [comment]
@SlicedDev How did you fix it? Can you show me the changes you made?

**Comment by ReyKoxha** [comment]
Updated and fixed.
