### ISSUE TITLE
Quartus, can't login to DB

### ISSUE THREAD

**Issue by ziez456** [ReyKoxha/Quartus_PUB#13]
Hello

I have a 2 quick questions
 
My database and everything is set up but i basically just can't connect because i don't know what i have to put here : https://i.imgur.com/ttWZcQl.png

And also how do i add users to the columns and pass and hwid?

**Comment by SlicedDev** [comment]
honestly, i think only dead @ReyKoxha knows how to properly connect quatus to db and other shit

**Comment by ziez456** [comment]
@SlicedDev O okay :(
Do you atleast know how to let it work without the login cuz when i delete the login.vb and change that line,, it opens up black and crashes..

**Comment by ziez456** [comment]
@ReyKoxha Did you read this?
Cuz his comment got deleted :)

**Comment by ReyKoxha** [comment]
@SlicedDev I am definitely not dead.
Just spare anyone from your useless comments here.

@ziez456 the instructions are indeed a bit unclear there.
You have to generate a key with which you encrypt a text.
I have used AES for this manner.

Alternatively you can change skip the login form by setting a different start from in the project settings:
1. Right-click on your project in solution explorer.
2. Choose properties.
3. Select the Application Tab.
4. Select your form from the dropdown under 'startup form'

The force close might occur due to outdated offsets, which I will update in a few minutes.

Regarding the login form - I can provide a little tool for encrypting & decrypting text the same was as in the login form.

**Comment by ziez456** [comment]
@ReyKoxha 
Thank you so much for your reaction and (Reaction time) damn!
Also i would really like to use the login, so it would be really cool if you could provide a little tool :)
And the offsets are outdated thats true :)
Thanks ALOT!

**Comment by ReyKoxha** [comment]
You are welcome @ziez456.
The only reason why I ignore the majority of posts is because most of the questions are brain dead.
However, in this case I do appreciate your effort to understand the code and try to help, which is the sense behind open source software.

Besides that I am either working on my car or due stuff for university, so no more CS:GO for me. ;)

**Comment by ziez456** [comment]
@ReyKoxha 
I understand bro!
Thanks
So is it possible to like provide that little tool :)
And the offsets
O ye btw in my database i got the table logins, with the columns username.passwd and hwid. How do i add my stuff in there?

**Comment by ReyKoxha** [comment]
I posted the SQL script here (auto export from MSSQL):
https://gist.github.com/ReyKoxha/1cb5c067602342d986bd0f9099c42ba2

You can insert data over a GUI tool like SQL Server Management Studio (SSMS).

Props go out to si0n by the way, who updated the base code!
https://github.com/iisp33dii/si0n-Source

Currently I am updating my IDE and will roll out the update for the cheat first, then release the code for the generator.

**Comment by ziez456** [comment]
Yes ive run that script,,

OO I GET IT NOW i think,,
So instead of using litterealy this
	[username] [varchar](50) NULL,
	[passwd] [varchar](50) NULL,
	[hwid] [varchar](50) NULL
i had to do this

	[myusername] [varchar](50) NULL,
	[mypasswd] [varchar](50) NULL,
	[myhwid] [varchar](50) NULL
?

Btw thanks alot for doing that!

**Comment by ReyKoxha** [comment]
These are not the data fields. These are the column names for the data.

**Comment by ziez456** [comment]
O wauw im auctually stupid..

But how do i add the data then?

**Comment by ReyKoxha** [comment]
Cheat is working again.
Swapped the default form to the executing one (skipping the login form).

Now to your question:
https://www.youtube.com/watch?v=uWIYfbtZat0

This video explains it all ;)

I will now get to the encryptor/decryptor.

**Comment by ziez456** [comment]
Thanks a a a lot

My power just went out cuz of the lightning but i will test it out

But i can still change the form so i can login right?

**Comment by ReyKoxha** [comment]
Of course you can, just change the start form in the project settings again.

Here is the promised encrypt/decrypt:
https://github.com/ReyKoxha/VB.NET-AES/

**Comment by ziez456** [comment]
Thanks so much so all i do now is encrypt my password? And encrypt my hwid? 
Btw what is the key then?

You updated the offsets right?

**Comment by ziez456** [comment]
Does it matter what aes i use?

Is the encrytpedtext the same as the key? 

Or i dont really know sorry

**Comment by ReyKoxha** [comment]
The cheat is working fine.
You have to encrypt your HWID & password as md5. To do this use a website like this:
https://www.md5hashgenerator.com/

To generate a key for the AES encryptor/decryptor just check its README.md.
The things you need are the encrypted text and the key.

**Comment by ziez456** [comment]
Thank you!
O okay so my password text and then the key is the encrypted of it? In aes?

And the md5 has to be in the data of the db?

**Comment by ReyKoxha** [comment]
The key is what is used to create the encrypted text.
The encrypted text is AES-CBC.

Correct.

**Comment by ziez456** [comment]
Okayy thankss alott!
For your time, for updating for helping me out and for your reaction time!!! Lots of love bro

**Comment by ziez456** [comment]
@ReyKoxha I don't know why but it still says when i try to log in
Login failed for user '****..
I did this https://i.imgur.com/dSRzpOy.png
Also tried AES-CBC but nope
so i did the key like this https://i.imgur.com/pNBWKWC.png
I added my data in my database so that worked

**Comment by ziez456** [comment]
@ReyKoxha 
Ive also tried this site: https://aesencryption.net/
Then i put my password of my database in the white box above and then the key i put "Login" so if you would decrypt it you should need the encryption result and the key and then you get my password
So i put at the login.vb this https://i.imgur.com/plggiXg.png
I thought that should work
But it also doesn't work..
