### ISSUE TITLE
Danger Zone Fix

### ISSUE THREAD

**Issue by BurakBalamir** [ReyKoxha/Quartus_PUB#15]
Hey bro can fix try danger zone update.

**Comment by DHJcheats** [comment]
Update pls

**Comment by ReyKoxha** [comment]
I will update the cheat as soon as new signatures are available.
As of now the only way fixing it, would be to run hard coded offsets, which would require a new release, whenever the signatures change.

Since I do not play CS:GO on a regular basis anymore, I will not provide a fix as of now.
