### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by xaze1337** [ReyKoxha/Quartus_PUB#16]
Bugs and improvements:
Mode2: Fov not working
Mode 2 on esp crashing after a while or suddenly disappears
no flash doesnt work at all
triggerbot seems edgy and doesnt hit sometimes
Aimbot not shooting new danger zone models

**Comment by ReyKoxha** [comment]
Unable to confirm any of these bugs.

Regarding Mode 2 ESP:
Most likely your system has excessive CPU load.
The code needs to be a bit cleaned up on that point.

Triggerbot:
Do not bind Trigger and Aim to the same key.

Danger Zone:
The cheat is not DZ ready.
It will only work in non-DZ mode.
