### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by pureLEM** [ReyKoxha/Quartus_PUB#2]
i downloaded visual studios and .net 4.7.1 but how do i compile the .snl folder or whatever im trying to compile? can you make a video tutorial or something!

**Comment by ReyKoxha** [comment]
I recommend that you check out how to "build" a project in Visual Studio. There should be more than enough on Google regarding this topic.

Please do not open tickets for stuff, which is unrelated to the code/repo itself.
