### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ReyKoxha** [ReyKoxha/Quartus_PUB#7]
Need confirmations regarding performance issues, since I am unable to reproduce them.
See #3

**Comment by SlicedDev** [comment]
i nave no fps issues with quartus on my i3-3220

**Comment by SlicedDev** [comment]
can you make tutorial on connecting quartus to mysql db, because i don't know what forms i should use for login/pass/hwid

**Comment by ReyKoxha** [comment]
Please open new tickets for each issue/question/suggestion arising @SlicedDev.
You simply need to rewrite the connector for the MySQL connector. There are plenty of tutorials on how to do it.

I will add the SQL script in a few minutes.

**Comment by ReyKoxha** [comment]
Tested with other systems - unconfirmed.
