### ISSUE TITLE
AimBot mode 2 broken.

### ISSUE THREAD

**Issue by 2ez4JAG** [ReyKoxha/Quartus_PUB#9]
Aimbot mode 2 is now completely broken, It doesn't work anymore.

**Comment by ReyKoxha** [comment]
Was tired yesterday.
Tested and fixed 94b4bde5d5769b6165879e3bd42c2a560bec2172.

**Comment by 2ez4JAG** [comment]
Its only working for pistol n sniper not for rifle.

**Comment by ReyKoxha** [comment]
Fixed 7f8893ec7db441ea4a09152cd0540c0a1daaf96c
